### ISSUE TITLE
Link to Clarity's new icon page is broken on Clarity Addons

### ISSUE THREAD

**Issue by d-m-s** [porscheinformatik/clarity-addons#1024]
## Describe the bug
Link to Clarity's new icon page is broken on Clarity Addons

## To Reproduce

1.  Go to '[https://porscheinformatik.github.io/clarity-addons/icons/get-started](https://porscheinformatik.github.io/clarity-addons/icons/get-started)'
2.  Click on button 'Get started' or Link "Clarity Icons - Get Started Guide"
3.  See error "404 ERROR Page not found
The link is broken or the page has moved.

## Expected behavior
Link to new page "[https://clarity.design/foundation/icons/](https://clarity.design/foundation/icons/)"

## Versions

**App**
- Addons Version 10.1.0
- Clarity Version 5.0.0

**Comment by Wallabeng** [comment]
Fixed
