### ISSUE TITLE
Brand avatar

### ISSUE THREAD

**Issue by d-m-s** [porscheinformatik/clarity-addons#1184]
**Is your feature request related to a problem? Please describe.**
Similar to the Letter Avatar, which shows the initials of an Person/Organisation, the vehicle need some clear and identifying/reoccuring badge.

**Describe the solution you'd like**
- Brand avatar showing the brand-logo on a square ground with rounded corners.
- The Shape is intentionally different to the Letter avatar, where a circle is used.
- Brand logos are available (see POI internal confluence, page "Logo, Theme, Icons")

**Usage**
<img width="823" alt="brand-avatar-usage" src="https://user-images.githubusercontent.com/311619/123269667-79ca9280-d4ff-11eb-8250-e12fa826d29f.png">

**Specs**
- bg-color, should be customizable via variable, default: #707070
- border radius: 2,5px
- width/height: 26px
- brand-logo: either max-width or max-height = 22px (height or width depending on the brand-logo, as large as possible maintaining a 2px padding to the square's border.)
<img width="442" alt="brand-avatar-detail" src="https://user-images.githubusercontent.com/311619/123269680-7b945600-d4ff-11eb-844e-dc7c3734f0f1.png">
- for foreign (non-company-brands) use new-car-private icon (https://porscheinformatik.github.io/clarity-addons/icons/icon-sets) 
<img width="49" alt="foreign-brand" src="https://user-images.githubusercontent.com/311619/123270264-0d03c800-d500-11eb-8d32-40ae8524b94a.png">

**Comment by Sylvain-Wehrum** [comment]
@d-m-s I will also set the color of the letter avatar to #707070 as default to match this

**Comment by Sylvain-Wehrum** [comment]
@d-m-s  Done. Available in version 10.3.0
