### ISSUE TITLE
ClrNumeric does not add disabled tag when its disabled property value is true

### ISSUE THREAD

**Issue by Blackleones** [porscheinformatik/clarity-addons#1214]
https://user-images.githubusercontent.com/10961232/125979670-c150a741-03a3-4df8-a0d0-8afc5068b3af.mp4

## Describe the bug

ClrNumeric does not add the disabled tag when its `disabled` property is set to true. Instead, the `clr-form-control-disabled` css class is applied. 
![img1](https://user-images.githubusercontent.com/10961232/125971516-de502646-081e-478f-b52b-78842f9835f1.png)
![img2](https://user-images.githubusercontent.com/10961232/125971523-a633556f-24b6-46f1-ac4f-62b661e3a2bd.png)

## To Reproduce

Create a form with an input, then put the `ClrNumeric` directive on it and set its initial disable value to `false`

## Expected behavior

`clr-form-control-disabled` is applied `disabled` tag is added to the input

## Versions
clr-addon: 10.1.0
clr: 5.0.1

**App**

- Angular: 11
- Clarity: 5.0.1
- Clarity-Addons: 10.1.0

**Comment by Wallabeng** [comment]
Fixed by #1219
