### ISSUE TITLE
Numeric input removing decimal places

### ISSUE THREAD

**Issue by rala72** [porscheinformatik/clarity-addons#1377]
## Describe the bug

I have an input field like below which removes leading zeros if I set the value to `1.5` via Angular for example.

```html
<input
  clrInput
  clrNumeric
  type="text"
  [(clrNumericValue)]="value"
  [clrUnit]="'%'"
  [clrDecimalSep]="','"
  [clrDecimalPlaces]="2"
  [clrAutofillDecimals]="true"/>
```

## To Reproduce

[StackBlitz](https://stackblitz.com/edit/clarity-numeric-field)

## Expected behavior

I don't want that, these decimal places are removed (replaced with zero).

## Versions

**App**

- Angular: 12.2.10
- Node: 14.17.4
- Clarity: 5.2.0
- Clarity-Addons: 10.4.1

**Device**

- Type: Laptop
- OS: Windows
- Browser: Chrome, Edge
- Version: 95.0.4638.69, 95.0.1020.53

**Comment by Wallabeng** [comment]
clrNumericValue is no longer a supported API and is only there for backwards compatibility.
Pls read/write values to the component using standard form handling.
See [NumericField documentation](https://porscheinformatik.github.io/clarity-addons/documentation/latest/numericfield) for reference
