### ISSUE TITLE
Error: export 'ɵbc' (imported as 'ɵbc') was not found in '@clr/angular'

### ISSUE THREAD

**Issue by matthewtquinn1** [porscheinformatik/clarity-addons#1465]
## Describe the bug

After upgrading Clarity and Clarity addons to their latest versions for my Angular app, when I try to build the app, I'm faced with the following error:

![image](https://user-images.githubusercontent.com/59854425/150512871-9ce64647-1fe6-4279-8a1a-a5e0609b7dc2.png)

## To Reproduce

1.  Create an Angular app (version 13.*)
2.  Install latest version of Clarity, Clarity Icons (clr/icons) and Clarity Add ons.
3.  Run `ng build  --configuration production`
4.  See build fail on error shown above

## Expected behavior

The angular application should be able to build.

## Versions

**App**

- Angular: [e.g. 13.1.2]
- Node: [e.g. 14.6.1]
- Clarity: [e.g. 13.0.0-next.1]
- Clarity-Addons: [11.0.1]

## Additional context

Is this a known bug with the different version, or have I missed a step on the upgrade process?

**Comment by Wallabeng** [comment]
Hy @matthewtquinn1,

Clarity-Addons is tightly coupled with clarity version, that's why a specific clarity version is specified as peer dependency in clarity-addons.
So for version 11.0.1 you must use clarity version 12.0.9 and angular 12 (as clarity itself is tightly coupled with angular).
All other combinations are not supported.

**Comment by matthewtquinn1** [comment]
Hi @Wallabeng,

Thanks for the reply and clearing that up! Is there a roughly estimated date for when Angular 13 will be supported? :)

**Comment by Wallabeng** [comment]
As soon as clarity officially releases v13, we will plan the upgrade. This should take no longer than 4 weeks from that point.

**Comment by jerone** [comment]
@Wallabeng With Angular & Clarity releasing at an higher pace, would it be possible to allow patches (`~`) or even minor (`^`) upgrades in your [`package.json`](https://github.com/porscheinformatik/clarity-addons/blob/master/package.json#L39-L50)? 

Right now all version are locked down, giving me failing `ng update`'s:

> Package "@porscheinformatik/clr-addons" has an incompatible peer dependency to "@clr/angular" (requires "12.0.9", would install "12.0.10").

**Comment by Wallabeng** [comment]
I can't do this with a good conscience, as we overwrite some css with our own styling, which can technically change in minors.
But if you use "ng update ... --force" you can ignore this, but are still able to review the messages manually.
