### ISSUE TITLE
Missing .scss files

### ISSUE THREAD

**Issue by jerone** [porscheinformatik/clarity-addons#1568]
## Describe the bug

In a few of our projects we have custom theme's setup for Clarity. We could do this very simple by importing all the required Clarity and Clarity Addons SCSS files in our themes. This allowed us to use all variables, while still applying the styling and extending where ever needed.

```
	@import '@clr/ui/src/utils/components.clarity'; // Clarity components.
	@import '@porscheinformatik/clr-addons/src/components.variables.clr-addons'; // Clarity Addons variables.
	@import '@porscheinformatik/clr-addons/src/components.clr-addons'; // Clarity Addons components.
```

However, in #1565 (and release 12.1.0.new) you removed the `src` folder (breaking change?), which also contained the `.scss` files. 

Would you consider adding those files back?
Perhaps move them to the `styles` folder?

## Versions

**App**

- Angular: 13.2.5
- Node: v16.14.0
- Clarity: 13.0.2
- Clarity-Addons: 12.1.0

**Comment by Wallabeng** [comment]
Hello @jerone,

thanks for pointing that out, it is actually a bug in the cpy-cli dependency we use to copy the SCSS files to the output folder:
https://github.com/sindresorhus/cpy-cli/issues/35

I downgraded the dependency (#1570) and we will wait for a fix to raise the version again.
12.1.1 contains this downgrade https://github.com/porscheinformatik/clarity-addons/releases/tag/v12.1.1
