### ISSUE TITLE
Display Default value for Datagrid Cell Values

### ISSUE THREAD

**Issue by FabianUntermoser** [porscheinformatik/clarity-addons#1602]
**Is your feature request related to a problem? Please describe.**
From a design perspective, indicating empty cells in a datagrid cell deliberately is better then just displaying nothing.

Before:
![image](https://user-images.githubusercontent.com/13196058/161535650-f11a4afd-6a62-4441-96f5-f8484a2ea2ab.png)

After:
![image](https://user-images.githubusercontent.com/13196058/161535735-038d4c9f-ca2a-4ceb-9664-108ea3977da5.png)

**Describe the solution you'd like**
Display a default value for DataGrid cells that might be null/empty.
Make the default value optional, and configurable. My suggestion is displaying a single dash `-`.
This way, everybody using the DataGrid, doesn't have to worry about displaying default values itself.

**Describe alternatives you've considered**
The alternative is that every application using the DataGrid component has to implement logic to handle displaying default values themselves. Pragmatically, only fields that are in fact optional or can be empty, need to be handled. A generic way to solve this issue for all fields could be nice.

The easiest but most repetitive option is to handle default values like this in the `.html` files.
```html
<clr-dg-cell>{{fieldThatIsEmpty || '-'}}</clr-dg-cell>
<clr-dg-cell>{{(dateFieldThatIsEmpty | date:'dd.MM.yyyy') || '-'}}</clr-dg-cell>
```
Moving this logic in the corresponding component class would be more sensible, but in the case of a date field formatted with an angular pipe, the pipe would overwrite the default value as it's not formattable as a date.

**Additional context**
I'm not sure if meddling with displayed values in a cell can be problematic in some cases.
But since Clarity and specifically the clarity-addons for POI are opinionated, I thought I should mention it.

**Comment by martinbrom** [comment]
@FabianUntermoser Getting back to this, one solution would be a directive for `clr-dg-cell` that checks the content on `AfterViewChecked`, and then replaces empty values with a placeholder of your choice - but even for small datagrids the performance takes a big hit, that's including batching DOM updates - you'd still have hundreds of directives active and hundreds of DOM updates. Even if it's more code, adding `(expression) || '-'` is the most performant option in my opinion.

I think we should close this as "wont-fix".
