### ISSUE TITLE
Missing icons on clr-brand-avatar since Angular v12 update

### ISSUE THREAD

**Issue by t-bthd43** [porscheinformatik/clarity-addons#1722]
## Describe the bug

Icons of clr-brand-avatar component don't load anymore since update to Angular v12.

![image](https://user-images.githubusercontent.com/31884836/176687724-41278d71-53bf-4065-bf6c-5c68124a822f.png)

## To Reproduce

Implemented as described in documentation: https://porscheinformatik.github.io/clarity-addons/documentation/latest/brand-avatar

## Versions

- Angular: 12.2.16
- Node: v14.15.5
- Clarity: 12.0.9
- Clarity-Addons: 11.0.0

**Comment by Wallabeng** [comment]
Starting with Addons v11 (Angular v12) you need to import the icons manually as stated in the upgrade guide
https://github.com/porscheinformatik/clarity-addons/releases/tag/v11.0.0
