### ISSUE TITLE
Loosen versions of Clarity

### ISSUE THREAD

**Issue by jerone** [porscheinformatik/clarity-addons#1821]
Would it be possible to loosen the supported versions of the Clarity dependencies?

Right now, those dependencies are [hard-coded](https://github.com/porscheinformatik/clarity-addons/blob/0136ba6f9061d135c3c6a4f9869e9d121fe8bac5/src/clr-addons/package.json#L23-L26), even on semver patch level.

I understand that `@clr/angular` & `@clr/icons` & `@clr/ui` are strong dependencies within this project. And that there is code depending on features of those dependencies.
Can I suggest adding tilde symbol `~` to get at least every update within the same minor range, because semver patch level should not include any breaking changes. 

For `@cds/core` I want to suggest adding an range of supported versions: `^5.6.0 || ^6.0.0`.
To keep in sync with what [Clarity suggests themselves](https://github.com/vmware-clarity/ng-clarity/blob/89858ae183837bbbf8a8241588db509bd09ee8fa/projects/angular/package.json#L23).

The reason for this is to get more control over what versions of Clarity we can use. And that we don't have to wait for Clarity Addons to support those versions.

![image](https://user-images.githubusercontent.com/55841/198007605-f03b77ed-b370-4eec-80ba-01e865092998.png)

Thank you, keep up the work on adding Addons!

**Comment by Wallabeng** [comment]
Hy @jerone!

yes, I think this should be possible.

Main reason for this was because we have overridden some CSS from clarity for our own theme.
But some releases ago clarity made theming more accessible through CSS3 variables and this shouldn't be that much of an issue right now.

Will take care of it as soon as I have some spare time, but if you want it immediately feel free to contribute a PR (main effort is needed in https://github.com/porscheinformatik/clarity-addons/blob/master/replace-versions.js).

**Comment by jerone** [comment]
You point out https://github.com/porscheinformatik/clarity-addons/blob/master/replace-versions.js, but that just takes the versions from https://github.com/porscheinformatik/clarity-addons/blob/master/package.json So I only have to update the versions there. But that also changes other projects (e.g. demo?).
But then those versions should be applied to https://github.com/porscheinformatik/clarity-addons/blob/master/src/clr-addons/package.json But the replacing variables are not there anymore since https://github.com/porscheinformatik/clarity-addons/commit/552d154185022b3201502a274f6c40908ef4cced#diff-9817c9329878b4e91645cf415b541911635f6b35a14868bc2e3dd3bddbf7c30b
And what does this file do: https://github.com/porscheinformatik/clarity-addons/blob/master/npm/clr-addons/package.json

I think I'll leave this up to you; it's all a bit confusing.

Thanks for considering.

**Comment by Wallabeng** [comment]
Ah yes you're right, replacing the dependency in package.json should be enough. My typing was faster than my thinking :)
Following procedure is executed:

1. copy https://github.com/porscheinformatik/clarity-addons/blob/master/npm/clr-addons/package.json to https://github.com/porscheinformatik/clarity-addons/blob/master/src/clr-addons/package.json
2. replace variables with replace-versions.js

**Comment by Wallabeng** [comment]
This would be the result now. Do you agree with that? https://github.com/porscheinformatik/clarity-addons/pull/1826

**Comment by jerone** [comment]
Yes, this allows us to update patch versions of `@clr/*` packages and minor versions of `@cds/core`. 👍
