### ISSUE TITLE
Angular 15 & Clarity 15

### ISSUE THREAD

**Issue by jerone** [porscheinformatik/clarity-addons#1886]
With Angular 15 being released many months ago, Clarity is finally [finalizing](https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.0.0-rc.2) it's effort to support Angular 15, for what time-frame can we expect Clarity Addons to support Angular 15 & Clarity 15?

_Keep up the great work!_

**Comment by Wallabeng** [comment]
Hi @jerone 
We are desperately waiting for clarity to finish release 15, so we can upgrade everything to that version. So expect an upgrade soon after clarity has finished the release.

**Comment by elgreco247** [comment]
Tada: https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.0.0

**Comment by Wallabeng** [comment]
We are working on the upgrade currently. So await a new version in the next few days.

**Comment by jerone** [comment]
I saw in the contributing file and your draft PR that you follow semver. Wouldn't it make sense to follow Angular versioning. It looks like Clarity is following that too. And many other packages are doing that also.

So, add support for Angular 15 and Clarity 15 in Clarity Addons version 15.

**Comment by martinbrom** [comment]
> So, add support for Angular 15 and Clarity 15 in Clarity Addons version 15.

We're going to change the versioning to follow the respective Angular/Clarity version 👍
