### ISSUE TITLE
clr-icon has been deprecated in favor of cds-icon

### ISSUE THREAD

**Issue by jerone** [porscheinformatik/clarity-addons#1903]
As stated [on their website](https://clarity.design/icons), `clr-icon` is deprecated, and `cds-icon` should be used.

>  clr-icon has been deprecated in favor of cds-icon. Please see the  [Core documentation](https://core.clarity.design/foundation/icons/)  for more details. 

![image](https://user-images.githubusercontent.com/55841/232789001-c4288930-3441-4277-94d8-a701a3388b77.png)

This project however [still uses it](https://github.com/porscheinformatik/clarity-addons/blob/master/npm/clr-addons/package.json#L25).

If removing is not an option, maybe not make it an peer-dependency, but an actual dependency, as new projects do not know this is an required dependency. Or update the [installation documentation](https://porscheinformatik.github.io/clarity-addons/documentation/latest/get-started#installing).

**Comment by jerone** [comment]
Example of component that needs to be converted is `clrSearch`:
https://github.com/porscheinformatik/clarity-addons/blob/f292d039d7732715becbc8e3ad8cad4469852416/src/clr-addons/searchfield/search-field.ts#L81
https://github.com/porscheinformatik/clarity-addons/blob/f292d039d7732715becbc8e3ad8cad4469852416/src/clr-addons/searchfield/search-field.ts#L93

**Comment by Wallabeng** [comment]
Hi @jerone!
yes you're right, we need to adapt our library by removing the outdated icons.
I will create a task at our internal task board.

**Comment by rala72** [comment]
Also, all styles have to be adapted, which is blocking us right now to upgrade all usages of our own.

**Comment by Wallabeng** [comment]
> Also, all styles have to be adapted, which is blocking us right now to upgrade all usages of our own.

Will also be handled in the adaption task

**Comment by jerone** [comment]
I recently did this for our internal products. 

Here are my global steps:
1. Replace all code references `<clr-icon` to `<cds-icon`.
2. Replace `class="is-solid"` to `solid` attribute.
3. Replace `class="is-error"` to `status="danger"`.
4. Replace `class="is-warning"` to `status="warning"`.
5. Replace `class="has-badge-info"` to `badge="info"`.
6. Replace `shape="caret down"` to `shape="angle" direction="down"`, and similar.
7. Create a new file `app.icons.ts` and add all icons in there:
```
import '@cds/core/icon/register.js';
import {
	angleIcon,
    ...
} from '@cds/core/icon';
/**
 * Load Clarity Core icons.
 * Keep list alphabetically to not add double icons.
 */
ClarityIcons.addIcons(
	angleIcon,
    ...
);
```
8. Reference this file in `app.module.ts`.
9. Remove any reference to clr-icons in `angular.json`.
10. Uninstall `@clr/icons` from your package.

There were a few icons that have new names. You'll find those when creating the icons list.

Useful links:
* https://clarity.design/icons
* https://core.clarity.design/foundation/icons/
* https://medium.com/claritydesignsystem/goodbye-clarity-icons-hello-clarity-core-adb07de9739e

**Comment by Wallabeng** [comment]
Is implemented by this
https://github.com/porscheinformatik/clarity-addons/releases/tag/v15.4.0
