### ISSUE TITLE
Does clarity-addons supports Angular 16?

### ISSUE THREAD

**Issue by kumar-tadepalli** [porscheinformatik/clarity-addons#1936]
## Describe the bug
I just found this awesome library. Our project is based on Angular 16.2.0.
We would like to use Clarity-addons. However, I have not seen any version compatibility/supportability data on the site.
What is the support window followed(LTS)?

Does clarity-addons supports Angular 16?

## Versions

**App**

- Angular: 16
- Node: 18.13.0
- Clarity: 15.9.1
- Clarity-Addons: 15.3.0

**Device:**

- Type: [e.g. MacBook]

**Comment by Wallabeng** [comment]
Hy,
the best way to see which versions we currently support is the package.json used for npm publish
https://github.com/porscheinformatik/clarity-addons/blob/master/npm/clr-addons/package.json
So yes currently we support 15 and 16 and we try to support the same versions as clarity
