### ISSUE TITLE
@kolkov/angular-editor not found

### ISSUE THREAD

**Issue by rala72** [porscheinformatik/clarity-addons#1976]
## Describe the bug

If I upgrade to version `15.3.0` or higher, I get the build error that `@kolkov/angular-editor` is not found.

## To Reproduce

Don't have `@kolkov/angular-editor` as dependency in your project and increase version to `15.3.0` or higher.

## Expected behavior

No build error.

## Versions

**App**

- Angular: 15.2.9
- Node: 18.8.0
- Clarity: 15.6.0
- Clarity-Core: 6.4.4 _(missing in template)_
- Clarity-Addons: 15.2.2 -> 15.5.6

**Comment by martinbrom** [comment]
Hi @rala72, I'm gonna look into the possibility of making the "angular-editor" an optional dependency. It is currently required for one of our components: https://porscheinformatik.github.io/clarity-addons/documentation/latest/html-editor. In the meantime, you can install the required dependency by running `npm i @kolkov/angular-editor@2.1.0` :)

**Comment by rala72** [comment]
are there any updates regarding a fix?

**Comment by martinbrom** [comment]
Resolved in version `17.3.0`.
