### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by repolevedavaj** [porscheinformatik/clarity-addons#2299]
Clarity finally released the Angular 18 compatibility, but this addons still depend on Angular 17. Are there any plans to release Angular 18 support? At least for clarity where no code changes needed, only in tests (see https://github.com/vmware-clarity/ng-clarity/pull/1440).

**Comment by martinbrom** [comment]
Hi, yes, the plan is to have a RC available in the next few days :) And a "proper" release after the RC is tested in a few of our internal apps.

**Comment by martinbrom** [comment]
@repolevedavaj `18.0.0-RC.1` is now available

**Comment by repolevedavaj** [comment]
Cool, thanks for the update.

**Comment by martinbrom** [comment]
18.0.0 is released (support for Angular 18)
