### ISSUE TITLE
External contribution to this repository

### ISSUE THREAD

**Issue by sdurnov** [porscheinformatik/clarity-addons#388]
Hi!

Very glad, that I found you addons!

I have a few questions:
1) Do you really accept external contributions?
2) If yes, is it possible to contribute only new components/utils, or I can propose modifications to existing addons?
3) Do you have any roadmap and release schedule? Do you release info prior to releasing breaking changes?
4) Is this repository a long-term project?

**Comment by Wallabeng** [comment]
Hello!

In general this project is used internally in our projects. So it's more like an internal library with open-source character.
The main reason for using GitHub was to be able to easily contribute to the Clarity repository itself. 
But if any external contributors have any useful components or changes to existing ones which fit our needs, we are happy to receive contributions also from an external source.

So to answer your questions:

1. Yes we do accept external contributions with some restrictions
2. If the contribution will fit our needs, it will be possible to create and also change existing implementations. But we won't implement stuff ourself, when internally there is no need for it.
3. We have no roadmap or release schedule, as this library grows on demand. There is also no info prior to a release, only the documentation page
4. It is a long-term project, as already some of our projects use it.

Hope this answers your questions!
