### ISSUE TITLE
Icon for Sidebar Pagelayout

### ISSUE THREAD

**Issue by KANekT** [porscheinformatik/clarity-addons#459]
How In collapse use icon 
![изображение](https://user-images.githubusercontent.com/580273/58633190-70ef3e80-82f0-11e9-87bf-a4d894b2d976.png)

in short view only icon
in full icon + nav text

**Comment by Wallabeng** [comment]
The Sidebar Pagelayout uses Vertical Nav of clarity, so just have a look there: https://v1.clarity.design/vertical-nav/basic-structure/charmander/
But basically: as soon as you use icons, they should appear in collapsed view without text

**Comment by KANekT** [comment]
Thx!
