### ISSUE TITLE
broken documentation links

### ISSUE THREAD

**Issue by ymanvieu** [porscheinformatik/clarity-addons#482]
hello,

the documentation links worked last week but somehow every links are dead now.

can you take a look ?

thanks.

**Comment by Wallabeng** [comment]
Hello!

"Every" link is not dead!
If you're talking about some of the links to clarity -> they should be fixed by next PR #479 , which is in review.
If it's not them, feel free to specify the links, so I can take a look!

Thanks!

**Comment by ymanvieu** [comment]
hello,

i mean this link : https://porscheinformatik.github.io/clarity-addons
the header itself and the link to the documentation are broken

**Comment by Wallabeng** [comment]
Ah yes this was a temporary defect, which is solved now!

Closing as it's fixed, otherwise feel free to reopen!
