### ISSUE TITLE
Make readonly configurable via boolean property

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#523]
Currently `readonly` (https://porscheinformatik.github.io/clarity-addons/documentation/latest/readonly) can only be applied or not applied. It would be great to use a boolean binding to toggle readonly (like disabled).

````html
<clr-checkbox-container [readonly]="shouldCheckboxesBeReadOnly">
</clr-checkbox-container>
````

**Comment by Wallabeng** [comment]
This is already possible with the attribute binding of angular, as null values prevent the rendering of the attribute:
`[attr.readonly]="shouldCheckboxesBeReadOnly ? true : null"`

It's a bit more boilerplate, but your suggested change is a breaking change, which I want to avoid.
I can take it as a requirement for the next major version.

**Comment by derkoe** [comment]
Thanks - that works! Would be great to have an example in the docs.

**Comment by Wallabeng** [comment]
Documented via #525
