### ISSUE TITLE
Angular 8 - ivy compatibility 

### ISSUE THREAD

**Issue by ymanvieu** [porscheinformatik/clarity-addons#565]
Hello,

having an angular 8.2 project, when enabling ivy and building the app, i get the error: 

> ERROR in No suitable injection token for parameter 'location' of class 'ClrBackButton'.
> no type or decorator

can you take a look ?

**Comment by Wallabeng** [comment]
Currently, clarity itself doesn't support ivy.
Until it's fixed there, we can't provide a solution for this.
See https://github.com/vmware/clarity/issues/3266

**Comment by ymanvieu** [comment]
hello @Wallabeng any update ?
with the Angular 9.0 release, Clarity design seems now compatible with ivy.
but with clarity/addons, build still fails

**Comment by Wallabeng** [comment]
not yet, as the current clarity release is not a release version (.next.8), but a release candidate

**Comment by ymanvieu** [comment]
I tried with the 2.3.7 release, and it was fine after upgrading to angular 9.0

**Comment by ymanvieu** [comment]
any updates ? since clarity 3.0.0 is released.

**Comment by Wallabeng** [comment]
We're already working on it (https://github.com/porscheinformatik/clarity-addons/pull/700).
But as we have a custom style, some critical adaptions are needed, to switch from SCSS to CSS3 which may take some time.
We also want to have some other breaking changes inside this change.

**Comment by ymanvieu** [comment]
glad to hear it ;)

**Comment by Wallabeng** [comment]
Release 7 is now live, so you may use it and should be finally able to activate ivy.
Will close this, as it should work.
