### ISSUE TITLE
Combobox validation

### ISSUE THREAD

**Issue by gurumaxi** [porscheinformatik/clarity-addons#690]
When the value in the combobox is empty and the component itself is blurred, the validation should be triggered. What about introducing a prop named required, if it is set, the validation is triggered when the value is empty.

**Comment by Wallabeng** [comment]
Currently we are trying to replace the combobox completely with the Datalist from clarity.
So maybe in the next release the combobox gets deprecated at all, as we strive to use clarity standard components.

**Comment by Wallabeng** [comment]
The combobox currently doesn't support forms at all and if we replace it anyways, we want to avoid that effort.

**Comment by d-m-s** [comment]
With the release of clr-addons 7.0 the Autocomplete Combobox is tagged "deprecated"

**Comment by Wallabeng** [comment]
Will be closed, as the component is deprecated now.
