### ISSUE TITLE
Internationalization example page, $ shown instead of € for language de-at.

### ISSUE THREAD

**Issue by d-m-s** [porscheinformatik/clarity-addons#807]
## Describe the bug

Go to clarity addons - internationalization page, there the $ currency symbol is shown instead of € for "de" locale.

![2020-05-20_14h28_13](https://user-images.githubusercontent.com/311619/82472165-09fe0300-9ac8-11ea-8671-a6d9184713b9.png)

## How to reproduce

1.  Go to 'https://porscheinformatik.github.io/clarity-addons/documentation/latest/internationalization'
2.  Select "de-at" or "de" in the Currency example table
3.  Verify example, see erroneous currency symbol: there the $ currency symbol is shown instead of €. 

## Expected behavior

"€" is shown for de, de-at -> verify that other languages work correctly

## Versions

Addons Version 8.0.1
Clarity Version 3.1.1

**Comment by Wallabeng** [comment]
Fixed with #811
