### ISSUE TITLE
Form validation causes button clicks to miss

### ISSUE THREAD

**Issue by ExtMuthM** [porscheinformatik/clarity-addons#814]
Describe the bug
---
When trying to submit a form contained in the edit block of a clr-view-edit-section at first the form is only re-validated. Only on second click the form is submitted.

This happens because the validation is triggered on blur and during the validation the form changes in height because error messages get displayed below certain fields.

This results in the save and cancel buttons changing position and therefore it is possible for the cursor to no longer be over the button and therefore not triggering the submit action when the click event is triggered.

Expected behavior
---
Submit event should be triggered regardless of form validation outcome

Versions
---
Addons Version 8.0.2
Clarity Version 3.1.3

**Comment by Wallabeng** [comment]
Hello @ExtMuthM 

as this is standard behavior in Clarity, we will not be modify it in this addons library.
As the view edit section just uses the clarity form fields.
If you want to address any change to this behavior, please talk to the clarity community.
