### ISSUE TITLE
View Edit section should change its editability according to clrEditable value

### ISSUE THREAD

**Issue by AbdelrahmanSaad** [porscheinformatik/clarity-addons#815]
On View Edit section the mode should be changed to VIEW when clrEditable is false in case it is currently on edit mode.

**Comment by Wallabeng** [comment]
Love to see a contribution for this

**Comment by d-m-s** [comment]
I'm currently trying to imaging a usecase when this is likely to happen ... ?
When entering the page it should already be clear according to rights whether editable is true or false, shouldn't it?

This can only happen when a view-edit-section (ves) is in edit-mode and a change happened dynamically (some interaction, background-action etc. took place and the rights are revoked) 

In these cases I guess a notification, validation-error from backend should be sufficient, an automatic change to view-mode may harm the user experience.

Or are there other usecases you currently think of?

**Comment by Wallabeng** [comment]
Closed as there are no usecases for this behavior. Feel free to reopen if there are some.
