### ISSUE TITLE
Angular 10 / Clarity 4 Update

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#823]
Update to Clarity 4 and Angular 10 and possibly provide `.next` builds like Clarity does before the release.

**Comment by derkoe** [comment]
The new clarity bundle does not export the internal classes in `clr-angular.d.ts` anymore, so theses kind of imports don't work:
```typescript
import { ɵb as RootDropdownService } from '@clr/angular';
```
@Wallabeng @cat-mandres any ideas?

**Comment by Wallabeng** [comment]
> Update to Clarity 4 and Angular 10 and possibly provide .next builds like Clarity does before the release.

As always I would wait until the final release of clarity is out, as we don't have the budget to make a .next build for every clarity .next build (And I don't think that the majority of our users is interested in this).

> The new clarity bundle does not export the internal classes in clr-angular.d.ts anymore

If these services aren't exposed anymore, we need to copy them to our repo (first guess).
