### ISSUE TITLE
Peer dependencies are wrong for 8.1.3 release

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#825]
The declared peer dependencies to `@clr/*` are 3.1.1 - the build used 3.1.3

https://github.com/porscheinformatik/clarity-addons/blob/v8.1.3/npm/clr-addons/package.json#L27 vs. https://github.com/porscheinformatik/clarity-addons/blob/v8.1.3/package.json#L45

**Comment by Wallabeng** [comment]
Fixed in 8.1.4 via #826
