### ISSUE TITLE
Treetable with fixed header scrolls out with longer content

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#839]
![treetable-header-fixed](https://user-images.githubusercontent.com/123199/88390001-dd13e800-cdb7-11ea-8135-2cdf9ae6f790.gif)

**Comment by Wallabeng** [comment]
Please provide a stackblitz, so I can give better/faster suggestions.

**Comment by derkoe** [comment]
Look at the demo app inside the project - after #842 there is an example now.

Or here is a StackBlitz showing all the issues https://stackblitz.com/edit/clarity-v3-light-theme-fa32z9

**Comment by derkoe** [comment]
This also seems to happen with Clarity's Datagrid - updated the StackBlitz

**Comment by derkoe** [comment]
Created an issue in the Clarity project https://github.com/vmware/clarity/issues/4824

**Comment by Wallabeng** [comment]
Thanks! As soon as clarity has a fix for that, we can integrate it into the treetable.

**Comment by d-m-s** [comment]
@Wallabeng
Clarity should be fixed, judging by the linked issue and current state of documentation ...
1. Can this issue be closed? 
2. Is further integration into treetable necessary?

**Comment by DaSmid** [comment]
Fixed with #2214
