### ISSUE TITLE
Numeric field remains invalid, after valid number is pasted into it.

### ISSUE THREAD

**Issue by walter-mair** [porscheinformatik/clarity-addons#862]
1) Enter a value, which fails to validate, and set the focus to the next field => you get 'clr-control-error' message
2) Copy a valid number to the clipboard, set the focus to the previous (faulty) field and paste the valid value into this field
3) Again set the focus to the next field => 'clr-control-error' message will stay and the form will stay invalid.

 

Example on Documentation page:

 

Copy '15' into the clipboard, below 'Vertical Form (Reactive)' type '-15' (negative 15) into the money field, hit 'tab' to set the focus to the 'Percentage field', you see the red message 'Please enter a value between 0 and 10.000'; hit SHIFT-'tab' to set the focus back to the 'Money' field, paste the clipboard content (positive 15) into the 'Money' field, hit 'tab' again to set the focus to the 'Percentage' field => the error message stays and the 'Money' field remains invalid!

 

It works fine,  in case you type '15' instead of pasting!

**Comment by mxab** [comment]
I'm also expirencing that issue when I select a value from chromes autofill
<img width="237" alt="chrome_input" src="https://user-images.githubusercontent.com/1607547/91346621-68cacb00-e7e1-11ea-8e43-09d9b6d90ef1.png">

when I select something from there the form is still not valid

<img width="154" alt="filled" src="https://user-images.githubusercontent.com/1607547/91346723-8b5ce400-e7e1-11ea-8d1e-50dca573bf00.png">

**Comment by Wallabeng** [comment]
Currently the numeric field works with keyup and keydown listeners. As both of your actions input data in a different way, those need to be handled as well.
Maybe a general "onChange" listener which validates after leaving the field would suffice for every case.
