### ISSUE TITLE
Content panel grows to the right instead of sliding from the right

### ISSUE THREAD

**Issue by Lasoloz** [porscheinformatik/clarity-addons#935]
## Describe the bug

When opening the content panel, the panel grows from the final position towards the right hand side of the browser window instead of going from the right to the left.

## To Reproduce

Just open the clarity addons content panel [demo](https://porscheinformatik.github.io/clarity-addons/full-page-layouts/content-panel)

1.  Click on the open button
2.  Click on the close button

Both transitions happen in an unexpected way, not matching visually with the intention.

GIF for future reference:

![__contentPanel](https://user-images.githubusercontent.com/17884077/95443582-696c8a80-0965-11eb-9c80-e939500921d8.gif)

## Expected behavior

The content panel should slide from the right with the left boundary moving from right side to the final position (right side - panel width)

## Versions

Locally, I experienced this issue with the following versions:

**App**

- Angular: 9.1.7
- Node: 10.15.3
- Clarity: 3.1.3
- Clarity-Addons: 8.1.2

**Device:**

- Type: Lenovo
- OS: Windows 10
- Browser: Google Chrome
- Version: 85.0.4183.121

**Comment by Wallabeng** [comment]
It seems to work when removing the "left" attribute on the content panel.
https://github.com/porscheinformatik/clarity-addons/blob/master/src/clr-addons/content-panel/content-panel.scss#L42
But this needs more testing, as I'm not quite sure why it was added.

@cat-mandres do you know why this "left" attribute exists?

**Comment by cat-mandres** [comment]
no, not anymore, would have to investigate

**Comment by d-m-s** [comment]
there is no necessity to provide an option to open the content-panel from the left side
- **default (and actually only) option should be right**. 
- so sliding in from right-to-left from the right side, would be the desired animation.


Please also remove the options to reduce confusions 
![2020-10-09_16h59_31](https://user-images.githubusercontent.com/311619/95599103-f3dde880-0a50-11eb-99cf-0bbb497c5da6.png)

**Comment by d-m-s** [comment]
valid and reproducible
