### ISSUE TITLE
Notification config to make box appear from bottom 

### ISSUE THREAD

**Issue by kjetilhp** [porscheinformatik/clarity-addons#957]
The notification box does stand out as clear when using a blue standard clr header, would be nice if it could take configuration saying that it should appear from the bottom (toastr like).

**Comment by Wallabeng** [comment]
Hello @kjetilhp,
currently it's not planned to implement something like this.
This project is also mainly used internally for our products, so we normally only implement features we need internally.
But feel free to contribute something if you need it. Before you do so, please clarify the specifications with us.
