### ISSUE TITLE
Responsive menu black overlay with screen widths below 576

### ISSUE THREAD

**Issue by kjetilhp** [porscheinformatik/clarity-addons#969]
## Describe the bug

Not sure if this css comes from your library or the old clarity version you are coupled with, but when screen width is below 576 the black overlay is in front of the menu, menues are not working. Not an css expert so not sure where this comes from but this appears when the width hits 575
@media screen and (max-width: 576px)
body {
    padding-top: var(--clr-header-height);
}
(from src/clr-addons/mobile.scss:31)

Having the same issue in my project as soon as I add the styling from this project, not when using the latest clarity styles.

## To Reproduce
your documentation site -> devtools -> responsive -> select phone or responsive -> screen width 575 - open either of the responsive hamburger menues - black overlay is in front of the menu

**Comment by kjetilhp** [comment]
This still applies for the 5.x release.

when 
```
@media screen and (max-width: 576px)
.main-container {
    display: block;
    overflow-y: auto;
}
```
(from mobile.scss line 35)
is applied (when resizing) the black overlay fills the entire screen in front of the menu. Looking at the file sm size is for some reason an input to the rules. Setting the max-width to a smaller number in devtools makes the overlay behave as normal on lower resolutions.

**Comment by d-m-s** [comment]
**Reproduced and added some screenshots below.**
@Wallabeng @cat-mandres can you guys take a look at this one.

Especially the right handed **option menu (vertical-dots)** is broken and unreadable:
<img width="320" alt="2021-06-24_15h50_55" src="https://user-images.githubusercontent.com/311619/123274665-024b3200-d504-11eb-89eb-efee812c8273.png">

Left handed, **Hamburger menu**:
<img width="310" alt="2021-06-24_15h51_07" src="https://user-images.githubusercontent.com/311619/123274674-02e3c880-d504-11eb-8dd6-3bd7d1747b69.png">

Comparison Clarity Screenshot (Note: Documentation Layout):
<img width="312" alt="2021-06-24_15h53_40" src="https://user-images.githubusercontent.com/311619/123275303-7d144d00-d504-11eb-9373-be21852681fc.png">

**Comment by kjetilhp** [comment]
They don't seem to bother with this, I guess they only use tablets at Porche. It would have been nice if it was stated clearly in the documentation that you can't target phones by using these addons.

As a workaround, I've cloned the repo, changed the size variable to sm, built and copied the clr-addons-phs.css to my project, and include that instead of the one from the package in angular.json.

**Comment by Wallabeng** [comment]
We do bother, but there is no dedicated team which maintains this library. It's more like a "if someone needs something, he needs to fix/implement it". So we simply don't have any capacity to fix anything if none of our projects complain about it.

The goal is indeed to also target phones with this, just because of this one bug you can't say it doesn't work at all on phones. But we also have dedicated "mobile-first" apps which use material, so this bug doesn't bother us that much, as most of clarity apps are used on tablet and bigger.

**Comment by kjetilhp** [comment]
Sorry if this came out wrong, however, non-functioning menus are quite a big deal when on mobile. Since you have so few issues and this has been around since before the 9 to 10 upgrade and the fix is only to change one variable to not override the clarity functionality I assumed it was intentionally overlooked.
